export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SET_ACCOUNT = "SET_ACCOUNT"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAILED = "SIGN_IN_FAILED"
export const LOGOUT = "LOGOUT"